### ISSUE TITLE
Create an Organization class and tab in the menu

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#106]
There are several organizations in the Fab Lab network: continental, national, regional, local associations and organizations. They are not labs, they are not users, but organizations. This has been requested and discussed for a while.

We need a specific type of entity in the db, backend, frontend, where such organizations are added, listed and managed. These organizations should be integrated with the discussion in [the Organization category on discuss.fablabs.io](https://discuss.fablabs.io/c/organization).

This is also related to #97 for the _discuss.fablabs.io_ integration.

**Comment by openp2pdesign** [comment]
The `Organization` class should be based on the `Lab` [one](https://github.com/fablabbcn/fablabs/blob/master/app/models/lab.rb), with these differences:

1. No machines
1. The geographical boundaries of the organization. boundaries should be part of [Administrative Levels in OpenStreetmap](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level). Ideally, we could query them with the [Overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API) (there's also a [gem](https://github.com/BrunoSalerno/overpass-api-ruby)), but it could be complex. So let's start with a simple approach: a form for the name of the area and then a checkbox to choose which level it is: 
    1. Global
    1. Continent
    1. Country
    1. State
    1. Region
    1. Province
    1. City

Admins will then check this and add the map of the boundaries, see #110

**Comment by openp2pdesign** [comment]
It seems that the best solution is **Nominatim**: http://wiki.openstreetmap.org/wiki/Nominatim
There's also a gem: https://github.com/jakubsvehla/nominatim

An example with Leaflet: https://derickrethans.nl/leaflet-and-nominatim.html

**Comment by openp2pdesign** [comment]
See for example this query for the _Poble Nou_:

`http://nominatim.openstreetmap.org/search?q=poble+nou&format=json&polygon=1`

**Comment by openp2pdesign** [comment]
Another interesting example is http://pelias.io/, especially for more advanced map browsing (later...). See also https://github.com/pelias/pelias-doc/blob/master/autocomplete.md

**Comment by openp2pdesign** [comment]
`Organizations` are approved by superadmins at the moment, no complex approval process like the one for the `Labs` is needed

**Comment by wendwarge** [comment]
@openp2pdesign Super pleased about this addition, thanks team io. I added Fab Antipodes, and saw that I can add the Labs that belong. but when I go to 'add Lab', only 30 labs are listed (mostly US) and the search function doesn't return results.

**Comment by openp2pdesign** [comment]
@ceritium we need to have at list a _Link_ field in _Basic details_ but ideally we would need the same fields for adding more links like in the `Project` section.

**Comment by ceritium** [comment]
@wendwarge did you used the search field?

![screen shot 2016-12-26 at 16 06 31](https://cloud.githubusercontent.com/assets/16633/21483809/f1408192-cb88-11e6-8b2c-2b3f4df99e1b.png)

**Comment by wendwarge** [comment]
Yes. Why I wrote: the search function doesn't return results.

**Comment by ceritium** [comment]
Sorry @wendwarge, Could you share me the link to the show page of the lab?

**Comment by wendwarge** [comment]
@ceritium sure! if you mean this:
https://www.fablabs.io/organizations/fab-antipodes/lab_organizations/new?utf8=%E2%9C%93&query=Fab+Lab+Wgtn&commit=Search
