### ISSUE TITLE
Search Results Bug

### ISSUE THREAD

**Issue by nnnnicholas** [fablabbcn/fablabs#159]
1. [Fab Lab du PEC](fablabdupec.com) does not show up in search results for "fab lab du pec" nor "fablab du pec" on [fablabs.io](fablabs.io).

2. We request that the page be renamed to match our official name: **Fab Lab du PEC**. The previous fab lab manager started but did not complete setting up the page for "Fab Lab du PEC." He is no longer affiliated with the lab. The correct name space for our lab is locked up in mid-creation process. Pamela King suggested we create a page as "Fablab du PEC." Our current URL is https://www.fablabs.io/labdupec. However, it is important that our lab be correctly listed on the network page and appear in search results so new and existing users can find us. 

Would you please correct our name, URL, and search results visibility?

We have been trying to revise our page name since 2015. Please help us correct our identity on fablabs.io. Please let me know when you have reviewed this message. Thank you!

Nicholas, Fab Tech
nicholas@fablabdupec.com

https://www.facebook.com/FabLabduPEC
https://www.instagram.com/fablabdupec/

**Comment by openp2pdesign** [comment]
1. The search engine currently searches in the slug, which in your case is _labdupec_. We are working on improving it, see #88 
1. There was a bug that complicated this operation, we are working on it, meanwhile me and @mverderau we will fix this manually

**Comment by openp2pdesign** [comment]
Here it is: https://www.fablabs.io/fablabdupec

**Comment by nnnnicholas** [comment]
Thank you for correcting our URL, @openp2pdesign & @mverderau.
Would it be possible to update our name, too? We would like to add a space: "FabLab" -> "Fab Lab".

![image](https://cloud.githubusercontent.com/assets/1418561/20860533/794bb44c-b948-11e6-87de-6dbbb1e5dd56.png)

**Comment by openp2pdesign** [comment]
Done: https://www.fablabs.io/fablabdupec

But these kind of requests are not properly bugs, so shouldn't be on GitHub :-)
