### ISSUE TITLE
Lab application status

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs#160]
There is no way for the user to check what is the status of their lab application. 

This is prone to people duplicate applications since they don't know if they have applied.

**Comment by openp2pdesign** [comment]
Yes, the plan is to make it completely transparent and visible

**Comment by hiromipaw** [comment]
@TheBeachLab Just wanted to point out that fablabs.io is an opensource project and while it is extremely valuable to receive feedback and have bug reported, it would also help to contribute to the project in more than one way.

**Comment by openp2pdesign** [comment]
The plan is to make the application process visible, and to let labs contact the supernodes and discuss with the community. But this will take a while to implement, there are more urgent bugfixes and such a process need to be carefully developed and tested. For this reason there's a whole Milestone for it: https://github.com/fablabbcn/fablabs/milestone/8

**Comment by TheBeachLab** [comment]
Sorry, actually they do know they have applied since they received a confirmation email and also they are receiving feedback about the rejection or approval from the referees. My mistake. Closing.

@hiromipaw I'd love to, I'm civil eng. not very good at programming but I have experience with databases. I feel like I could be able to contribute more if I would be able setup some sort of virtual machine with a sandbox installation for tweaking here and there. I'm not sure if what's here in this repository is self contained project or it depends on other pieces
