### ISSUE TITLE
Lab application form field ends up in discuss?

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs#161]
I recently helped to submit lab applications to 20 minilabs in Kerala India. Somehow they filled up a field that ended up in discuss.fablabs.io I don't know how they ended there and what is that field but defibitely is confusing and this should not happen.

**Comment by openp2pdesign** [comment]
@TheBeachLab  which field? Could you post a screenshot?

**Comment by openp2pdesign** [comment]
@TheBeachLab  and links, please. Generally, the more information we have, the easier it is for checking the situation.

**Comment by TheBeachLab** [comment]
@openp2pdesign please checkout these 20 new discussions open in discuss https://discuss.fablabs.io/c/labs I think that when you set up a new lab https://www.fablabs.io/new if you fill-in the field **ANYTHING ELSE? Application notes**, I think that these notes open automatically a discussion in discuss

**Comment by openp2pdesign** [comment]
@ceritium Please check that new lab / project / machines thread on Discuss have only the _description_ field and nothing more, and please edit or re-import existing threads accordingly. 

At the moment, each thread at the end have a link to the main page on Fablabs.io, which is great, we should just have something like:

> This is the general thread for discussing the lab; the thread is also visible on its page at https://www.fablabs.io/minifablabrit

**Comment by TheBeachLab** [comment]
Yes @openp2pdesign , it is the description field what is shown. But why do it opens a discussion? Has every lab a discussion page even if they did not open any discussion?

**Comment by openp2pdesign** [comment]
@TheBeachLab Is it the _Description_ or the _ANYTHING ELSE?_ field?

**Comment by openp2pdesign** [comment]
Each lab, machine and project will have an automatically created thread on the _Discuss_ section in order to enable a community discussion. Then, of course, further threads can be created, but this is the starting point. This replaces the Disqus commenting system, for several reasons.

**Comment by openp2pdesign** [comment]
So, as a conclusion for @ceritium:

- if the field that's included in _Discuss_ is _ANYTHING ELSE?_, this should be removed, only the _ Description _ field should be included in the threads at the moment
- If possible, fix this: each thread at the end have a link to the main page on Fablabs.io, which is great, we should just have something like:

> This is the general thread for discussing the lab; the thread is also visible on its page at https://www.fablabs.io/minifablabrit
