### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#180]
There are several languages available for the UI, we need at least the Portuguese one now, and this has been requested by some users. So, as soon as somebody provide the translation as a comment in this issue, we will add it. When this is ready, me and @mverderau will add the translation to the db and uncomment this line to make the Portuguese translation active: https://github.com/fablabbcn/fablabs/blob/935314e2955461ec675deda836022988c4083d07/app/views/layouts/application.html.haml#L70

Here are the English sentences to be translated to Portuguese:

1. Laser Cutting/Engraving
1. Settings
1. Circuit Production
1. Machines
1. CNC Milling
1. 3D Printing
1. Sign in
1. Fab labs provide widespread access to modern means for invention. They began as an outreach project from MIT’s Center for Bits and Atoms (CBA), and became into a collaborative and global network. You can find more information about Fab Labs on the % {fab_foundation} Website. The annotated photo below illustrates the facilities of a typical Fab Lab.
1. Vinyl Plotter
1. Show me Fab Labs
1. Who is fablabs.io for?
1. Lab Profiles
1. What's coming next?
1. What can I do?
1. Opening Hours
1. Me
1. List
1. Sign out
1. Developer API
1. Machines
1. Forum
1. Welcome
1. Labs
1. Precision Milling
1. And beyond that?
1. Around the World
1. Events
1. Sign up
1. Map
1. Backstage
1. Activity Feeds
1. Search Labs...
1. All Countries
1. Localisation
1. Events
1. World Map
1. I'm new here. What's a Fab Lab?

**Comment by maujabur** [comment]
Hi!
I can help you with the translation this weekend. 
Some words need a bit of context in order to have a good translation, for instance: "me" and "sign up".
The first one, me, because it can be used as in "tell me" and as in "for me" and it uses different words in Portuguese. 
Also verbs, like sign up, sometimes can be in first person or on the infinitive form.

**Comment by openp2pdesign** [comment]
Thanks @maujabur! I'd say:

1. me = "For me" (it would be: "My account")
1. "Sign up" is the same as "Register your account"

**Comment by waldooo** [comment]
**1. Corte Laser/Gravação
2. Configurações
3. Produção de circuitos
4. Maquinas
5. Usinagem CNC
6. Impressão 3D
7. Entrar**

**Comment by maujabur** [comment]
Hi! I'll begin with those 2 now. We have a discussion group here in Brazil, and there are more people who want to help. They may appear later.
1. "For me"= "Para mim" (me = mim)
"my account" = "minha conta"
2. "Sign up" = "cadastre-se" (imperative form)

**Comment by waldooo** [comment]
9. Plotadora de Vinil
10. Mostre-me Fab Labs
11. Para quem é voltado o fablabs.io?

13. O que está para vir?
14. O que posso fazer?
15. Horários de Funcionamento
16. Minha Conta
17. Listar
18. Sair

20. Máquinas
21. Forum
22. Bem-vindo
23. Laboratórios
24. Usinagem de precisão
25. E além disso?
26. Ao redor do mundo
27. Eventos
28. Registrar-se
29. Mapas
30. Bastidores
31. Feed de Atividades // alguém tem uma tradução melhor para feed? Parece uma palavra que já é comum em português...
32. Procurar por Laboratórios...
33. Todos Países
34. Localização
35. Eventos
36. Mapa Mundial
37. Sou novo aqui. O que é um Fab Lab?

**Comment by maujabur** [comment]
I think item 12 is not right...

> O que está para vir?

**Comment by waldooo** [comment]
`I think item 12 is not right...

O que está para vir?`

Maybe: O que está por vir?

**Comment by waldooo** [comment]
I got it now!
I've made a numbered list and erased some itens... it renumbered and now it is all wrong. I'll fix that

**Comment by openp2pdesign** [comment]
So:

| English | Portuguese |
|---------|------------|
| Laser Cutting/Engraving | Corte Laser/Gravação |  
| Settings | Configurações |  
| Circuit Production | Produção de circuitos |  
| Machines | Maquinas |  
| CNC Milling | Usinagem CNC |  
| 3D Printing | Impressão 3D |  
| Sign in | Entrar |  
| Fab labs provide widespread access to modern means for invention. They began as an outreach project from MIT’s Center for Bits and Atoms (CBA), and became into a collaborative and global network. You can find more information about Fab Labs on the % {fab_foundation} Website. The annotated photo below illustrates the facilities of a typical Fab Lab. | Fab Labs fornecem um acesso amplo aos meios modernos de invenção. Eles começaram como um projeto de extensão do Center for Bits and Atoms (CBA) do MIT, e se tornaram uma rede colaborativa e global. Você pode encontrar mais informações sobre Fab Labs no site % {fab_foundation}. A foto abaixo ilustra as instalações de um Fab Lab típico. |  
| Vinyl Plotter | Plotadora de Vinil |  
| Show me Fab Labs | Mostre-me Fab Labs |  
| Who is fablabs.io for? | Para quem é voltado o fablabs.io? |  
| Lab Profiles | Perfil dos Laboratórios |  
| What's coming next? | O que está por vir? |  
| What can I do? | O que posso fazer? |  
| Opening Hours | Horários de Funcionamento |  
| Me | Minha Conta |  
| List | Listar |  
| Sign out | Salir |  
| Developer API | ... |  
| Machines | Máquinas |  
| Forum | Forum |  
| Welcome | Bem-vindo |  
| Labs | Laboratórios |  
| Precision Milling | Usinagem de precisão |  
| And beyond that? | E além disso? |  
| Around the World | Ao redor do mundo |  
| Events | Eventos |  
| Sign up | Registrar-se |  
| Map | Mapas |  
| Backstage | Bastidores |  
| Activity Feeds | Feed de Atividades |  
| Search Labs... | Procurar por Laboratórios... |  
| All Countries | Todos Países |  
| Localisation | Localização |  
| Events | Eventos |  
| World Map | Mapa Mundial |  
| I'm new here. What's a Fab Lab? | Sou novo aqui. O que é um Fab Lab? |  

@waldooo what about _Developer API_? Is it _Lista_?

**Comment by waldooo** [comment]
Sorry  @openp2pdesign ,  my mistake. 
"Developer API" should be "Desenvolvedor API"

**Comment by openp2pdesign** [comment]
@maujabur @waldooo Amazing! It's now active! We will update this when the new interface will be ready!

Btw: _Minha Conta_ is too long for the current interfaces and it breaks the design, that's why I put _Me_ ...
