### ISSUE TITLE
I can't save the modifications I do on fablab digiscope's profile

### ISSUE THREAD

**Issue by romaindivozzo** [fablabbcn/fablabs#212]
After modifying contents on the Fablab Digiscope's profile, when I click on the "save" button, it concludes with a message that says that "we are sorry, an error occurred...".

Second thing, I cannot validate the french fablab network in the Orgs tab. It sends an error message about requesting the wrong page.

bye
romain

**Comment by mverderau** [comment]
Hi Romain,

How are you?

We`re developing the new platform, fixing all the bugs and improving the
processes to give a better experience.
That`s why some functions are still not working. The organizations will
take a little bit longer than the contents.

I`ll send your case to the developer to make a review.

Please remember that you can help us in many ways, to improve and fix this
problems at Github and Discuss.

Best,
Matias



Matías Verderau

Community Leader

Making Sense Fablabs.io

FabLabBCN @ IaaC Network Manager

E   matias@fablabbcn.org

M  +34657494523

www.making-sense.eu

www.fablabbcn.org

www.iaac.net

www.fablabs.io


twitter.com/MakingSenseEU

facebook.com/MakingSenseEU



Veure Avis legal de protecció de dades i confidencialitat
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

See Legal Data protection and confidentiality
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

Ver Aviso legal de protección de datos y confidencialidad
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

**Comment by openp2pdesign** [comment]
Hello Romain,
could you post some screenshots of the errors? It would be easier to check it.

**Comment by openp2pdesign** [comment]
@romaindivozzo I can edit it without a problem and I can see the edited details on the page.
We need to know:

- which details you edited
- which error messages you got

**Comment by openp2pdesign** [comment]
And regarding:

> Second thing, I cannot validate the french fablab network in the Orgs tab. It sends an error message about requesting the wrong page.

Please check it again, and if the problem persists please open a separated issue (it's another bug!)

**Comment by romaindivozzo** [comment]
Massi,

It is working like a charm now. I was able to accept that fablab digiscope would become one of the labs listed under the R?seaux Fran?ais des Fablabs.

I've posted a message on the french network forum so the other labs should start doing the same.

Keep going guys you're doing a hell of a good job.

romain

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________
