### ISSUE TITLE
"Accept add lab to organization" email template not executed

### ISSUE THREAD

**Issue by loic-fejoz** [fablabbcn/fablabs#213]
Hi,

I just received an email with the template and not the content.

> Hi,
> 
> Your lab #{@lab) was proposed to be part of the organization #{@organization}
> 
> Please accept or reject the invitation: #{organization_lab_organization_url(@organization, @lab_organization)}

**Comment by mverderau** [comment]
Hi Loïc,

How are you?

We`re developing the new platform, fixing all the bugs and improving the
processes to give a better experience.
That`s why some functions are still not working well.

I`ll send your case to the developer to make a review.

Please remember that you can help us in many ways, to improve and fix this
problems at Github and Discuss.

Best,
Matias



Matías Verderau

Community Leader

Making Sense Fablabs.io

FabLabBCN @ IaaC Network Manager

E   matias@fablabbcn.org

M  +34657494523

www.making-sense.eu

www.fablabbcn.org

www.iaac.net

www.fablabs.io


twitter.com/MakingSenseEU

facebook.com/MakingSenseEU



Veure Avis legal de protecció de dades i confidencialitat
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

See Legal Data protection and confidentiality
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

Ver Aviso legal de protección de datos y confidencialidad
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

**Comment by openp2pdesign** [comment]
@ceritium was it fixed with 6d51373917b5a62abcdd9b9180a217677358096b ?

**Comment by ceritium** [comment]
yes

**Comment by openp2pdesign** [comment]
It seems to be still an issue: https://discuss.fablabs.io/t/french-labs-cannot-be-added-to-the-french-fablab-organization-rff/1724

**Comment by lespacedunmatin** [comment]
Looking at the dates and seing that the issue has been opened by Loïc, I think that you closed the issue, but I need to be able to send again the emails to the labs I want to invite into the Org “Réseau Français des FabLabs”.

**Comment by loic-fejoz** [comment]
I have never received the email again indeed.
But now, when going at https://www.fablabs.io/backstage/labs I can click on a lab and approve it (done on Thilab).

**Comment by openp2pdesign** [comment]
@lespacedunmatin I imagine that emails are sent automatically once you add the Labs, but that they cannot be sent again (something we should add, right)... is it correct?

**Comment by openp2pdesign** [comment]
... and we should also, if possible and promising, change notifications from e-mails to _Discuss_ messages and threads as in #252

**Comment by lespacedunmatin** [comment]
@openp2pdesign : yes, this is correct, the emails cannot be send again. I tried today by adding again the labs.

**Comment by openp2pdesign** [comment]
ok, great! @lespacedunmatin @loic-fejoz @romaindivozzo is this the only problem?

**Comment by lespacedunmatin** [comment]
@openp2pdesign : so are the labs that recieved an incorrectly formated message stuck in pending mode ? Could you remove all the pending labs, that would allow me to add them again.

**Comment by openp2pdesign** [comment]
@lespacedunmatin are they all pending except (Fab)Lab Digiscope?

**Comment by lespacedunmatin** [comment]
@openp2pdesign : yes, that’s what I see.

**Comment by openp2pdesign** [comment]
@lespacedunmatin we need another feature for this, #253

**Comment by openp2pdesign** [comment]
@lespacedunmatin @loic-fejoz @romaindivozzo if there are no further comments here (especifically regard the e-mail template), let's move the discussion to #253 for more advanced communication and managing features
