### ISSUE TITLE
Palestine not listed as country

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs#224]
Palestine is not registered as country not when individuals register or you want to set a lab there
https://en.wikipedia.org/wiki/State_of_Palestine

**Comment by TheBeachLab** [comment]
Sorry wrong place, this is Fab Academy related, not fablabs.io

Closing

**Comment by openp2pdesign** [comment]
Yes, Palestine can be added via Google Maps autocomplete form...
