### ISSUE TITLE
Discourse SSO

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#238]
It seems that it is possible to implement a Single Sign On (SSO) between Discourse (_Discuss_) and Fablabs.io, we should set this up in order to make easier for everybody to join the discussion:

- https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045
- https://meta.discourse.org/t/sso-for-dummies/50243
- https://meta.discourse.org/t/discourse-api-login-case-sso-provider-to-consumer-site/48441

Also, the Discourse user (with OAuth from Fablabs.io) should be generated automatically when the Fablabs.io user is created.

**Comment by openp2pdesign** [comment]
https://meta.discourse.org/t/how-to-import-sso-users/25139

**Comment by ceritium** [comment]
From https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045

![screen shot 2017-02-16 at 11 14 38](https://cloud.githubusercontent.com/assets/16633/23017069/2aa920f0-f439-11e6-9e1a-4276e6e1470f.png)

Fablab do not validate the email.

**Comment by openp2pdesign** [comment]
Fixed with 87841fab5fb613dc01e4b1e5535aa9d1409ed1bc
