### ISSUE TITLE
webmasters@fablabs.io email address not valid

### ISSUE THREAD

**Issue by bill3721** [fablabbcn/fablabs#348]
when sending emails to webmasters@fablabs.io
returns with the following error message

DM3NAM03HT198.mail.protection.outlook.com

webmasters@fablabs.io
ak47
Remote Server returned '550 5.1.351 Remote server returned unknown recipient or mailbox unavailable -> 554 Unknown recipient'

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=msn.com; s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=XmcEuFf1W7rr65AcFCYF1KV0kHeZErzpbm2qrUUg1QE=;
 b=S/8X7cMDIkl8grxpRq5Fr42s4JWTtRWZuf6TBSoTKg3L51vz7ytRcDgWbQh6PDVLu5SpP/YGBiPGkMvdcX8e8DUdNi+kacEX1PrmoRhqupagUUwE4z21FDluh5VcyAvWp8bDhA4tVsE6gSztYwNO1l/SSLxBjDkhf7ihcVBwW3ShEkUefCWbJQ+QfN8tty0CSph+2NOg0rWmSTl8VYJ3TQAy01Z1DCt14JONyaje0g2wgUtupOeaHyLSr4bahsg+hsrFTl2UWauXif86D2uO3kb1aknRA4gMuqJRPw+7xAGEdhaaOnJYfxmV8QzEjsltNmtDj2l2un22zX7Jc2XunA==
Received: from DM3NAM03FT062.eop-NAM03.prod.protection.outlook.com
 (10.152.82.52) by DM3NAM03HT198.eop-NAM03.prod.protection.outlook.com
 (10.152.83.62) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.1.1341.15; Thu, 17
 Aug 2017 10:21:52 +0000
Received: from DM5PR19MB1514.namprd19.prod.outlook.com (10.152.82.58) by
 DM3NAM03FT062.mail.protection.outlook.com (10.152.83.142) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id
 15.1.1341.15 via Frontend Transport; Thu, 17 Aug 2017 10:21:52 +0000
Received: from DM5PR19MB1514.namprd19.prod.outlook.com ([10.173.211.144]) by
 DM5PR19MB1514.namprd19.prod.outlook.com ([10.173.211.144]) with mapi id
 15.01.1362.018; Thu, 17 Aug 2017 10:21:52 +0000

**Comment by mverderau** [comment]
Hi Bill,

I`ve just saw your message.

How can I help you?

Please let me know if you receive this mail.

Best regards,
Matias



Matías Verderau

Community Leader

Making Sense Fablabs.io

FabLabBCN @ IaaC Network Manager

E   matias@fablabbcn.org

M  +34657494523

www.making-sense.eu

www.fablabbcn.org

www.iaac.net

www.fablabs.io


twitter.com/MakingSenseEU

facebook.com/MakingSenseEU



Veure Avis legal de protecció de dades i confidencialitat
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

See Legal Data protection and confidentiality
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

Ver Aviso legal de protección de datos y confidencialidad
<http://iaac.net/legal-notice-data-protection-and-confidentiality/>

**Comment by openp2pdesign** [comment]
@bill3721 it seems to be working now, please let us know if you still have any issue
