### ISSUE TITLE
Weird. Lab disappears on the map when zooming in

### ISSUE THREAD

**Issue by TheBeachLab** [fablabbcn/fablabs#356]
The manager of the lab spotted this issue. This mini-lab in India:
https://www.fablabs.io/labs/minifabasiet
Appears on the map until a certain level of zoom. Look at the 3 labs in line:
![screenshot_2017-09-14_17-05-14](https://user-images.githubusercontent.com/5508720/30440836-94a6fb86-996f-11e7-9436-3b32e1e3a199.png)
When you zoom in the bottom one disappears, but the link is still there and you can click on it.
![screenshot_2017-09-14_17-05-53](https://user-images.githubusercontent.com/5508720/30440950-de855608-996f-11e7-8641-415cf3831d88.png)
Tested in Windows+Chrome and Linux+Firefox

**Comment by openp2pdesign** [comment]
It happens alsow with https://www.fablabs.io/labs/rajagiri

This seems to be the problem:
```

mini_fab_lab70.png Failed to load resource: the server responded with a status of 404 ()
mobile70.png Failed to load resource: the server responded with a status of 404 ()
```

**Comment by openp2pdesign** [comment]
It should be fixed now, there are no specific icons for mobile and mini lab at the moment, hence the error.
