### ISSUE TITLE
Verification e-mails are not sent

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#374]
When a `User` registers, the platform says that a verification e-mail is sent, but these are currently not received...

**Comment by TheBeachLab** [comment]
Is there any temporary workaround on this issue?

**Comment by openp2pdesign** [comment]
It's probably an issue in the infrastructure, we haven't deployed new code in a while. @viktorsmari is working on it

**Comment by hiromipaw** [comment]
You just have to restart redis and it will work.

**Comment by openp2pdesign** [comment]
It was a problem with Sidekick, fixed now
