### ISSUE TITLE
Problem with map visualization

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#42]
<img width="1094" alt="screen shot 2015-07-15 at 21 11 56" src="https://cloud.githubusercontent.com/assets/1458229/8707470/31f95ba4-2b36-11e5-9761-7d0ee65e2f2e.png">

The [map page](https://www.fablabs.io/map) is cut in a weird way at the moment: it is very short and there's a lot of empty white space under it. Google Chrome on Mac (both updated). 
It did work well in the morning.

**Comment by hiromipaw** [comment]
Thanks for reporting this. Will look into it.

**Comment by hiromipaw** [comment]
Hey we had a problem when updating foundation. I think this is now fixed :) Thanks for reporting.
