### ISSUE TITLE
Lab added in August 2015 not yet approved 

### ISSUE THREAD

**Issue by 5N44P** [fablabbcn/fablabs#67]
Hi 
I added my lab on 22 august 2015. 
Few days later i've recieved this mail: 

"Hi Valerio,
Your lab Fablab Bergamo, was approved by the designated referee it is now awaiting for admin approval. -"
When will it be approved? 
Thank you

**Comment by 5N44P** [comment]
Any update?
Thanks

**Comment by Fablabimpact** [comment]
Any update on what ?

Enviado desde mi iPhone

**Comment by 5N44P** [comment]
I would like to know whether my lab will be approved by admin or not... 

Kindest regards

**Comment by openp2pdesign** [comment]
The lab was approved recently: https://www.fablabs.io/fablabbergamo
