### ISSUE TITLE
Can't see lab to be approved in my list 

### ISSUE THREAD

**Issue by fibasile** [fablabbcn/fablabs#80]
I wanted to approve a lab named poplab (who had me as reference) but couldn't find it in my list.

If this could help, the notifications popup on top right marks 30 pending actions, while the lab review pane marks 22.

I was able to approve poplab going directly to https://www.fablabs.io/backstage/labs/poplab.

**Comment by openp2pdesign** [comment]
The lab has been recently approved: https://www.fablabs.io/poplab

But I'll keep the issue open in order to fix the bug
