### ISSUE TITLE
error with lab approval process 

### ISSUE THREAD

**Issue by wydmynd** [fablabbcn/fablabs#81]
I am helping set up a new lab in Kiev, Ukraine. the lab is up and submitted for review as a mini lab "fabricator", and approved by Wendy from NZ and Ohad from IL (I am in contact with Ohad for help with the approval process) 
Ohad claims the approvals have been fed in the system but the lab does not appear on the list.

could be related to issue #80 lab was submitted on April 6th

Please help us revive the Ukrainian maker and fabber community! 
A lot of work has been put in to the lab and being listed as a mini lab can help the founders get grants, and other help to keep the lab open!
see images at - https://goo.gl/zJAAUR

contact me for details at - fablab ($$) madatech.org.il
thanks
Tom from Fablab Haifa, Israel.
Maksym from Fabricator lab, Kiev, Ukraine

**Comment by openp2pdesign** [comment]
The lab has been recently approved: https://www.fablabs.io/fabricator
