### ISSUE TITLE
Can't see lab to be approved in my list or read message 

### ISSUE THREAD

**Issue by ohadme** [fablabbcn/fablabs#82]
I wanted to approve a lab named poplab (who had me as reference) but couldn't find it in my list.
I can see that I have a message in my backstage but can't read it.

Ohad Meyuhas

**Comment by archited** [comment]
I had the same problem as Ohad, the backstage didn't really show all the history of labs who put our lab as a reference lab. Another issue is, the system sent emails to all the people list in our lab, whenever some one click approve, it approved as I did, which I didn't,  someone just did it mistakenly and there's no way we can track it. There's already some labs been approved that way. So I removed everyone list under our lab first.

**Comment by wendwarge** [comment]
Same problem here, now that we're on the list of supernodes. Got 2 messages and can't find them.

**Comment by openp2pdesign** [comment]
Also related to #80

**Comment by openp2pdesign** [comment]
@ceritium  Let's save also the user who rejected or approved or else the lab in the db
> Another issue is, the system sent emails to all the people list in our lab, whenever some one click approve, it approved as I did, which I didn't, someone just did it mistakenly and there's no way we can track it.

**Comment by openp2pdesign** [comment]
@ceritium The referees should see in the backstage two tabs, _My labs_ and _Labs to approve_

**Comment by ceritium** [comment]
I fixed the method that show in the header pending labs for referees.  The current list of labs in backstage looks fine. Could we close the issue?

**Comment by openp2pdesign** [comment]
@ohadme @wendwarge @archited @fibasile (see #80) is it ok now?

**Comment by wendwarge** [comment]
@openp2pdesign Can you send me a fake lab to approve? I haven't got anything backstage to see. will send you a snap of what I see.

**Comment by openp2pdesign** [comment]
@wendwarge sent! Let me know...

**Comment by wendwarge** [comment]
@openp2pdesign what's app'd you an image

**Comment by wendwarge** [comment]
I don't have a red message by my photo letting me know there's a message. following the email link is still the only way I can find new labs for approval. I don't have two tabs saying 'my labs' and 'labs to approve. I have labs that I didn't approve on my list of labs, and labs that I did approve aren't on my list. Is that last one a different issue? Screenshot
<img width="776" alt="backstageview" src="https://cloud.githubusercontent.com/assets/16007251/21411213/8fe7f438-c84b-11e6-9eb6-6b916aa638a5.PNG">

**Comment by ceritium** [comment]
I fixed the method that display the "red badge" of pending labs for approve.  

It's probably that old labs was approved by a superadmin, then you will not find them in the list.

Finally I didn't implement the new list of labs pending of approve, because the current one works fine (I think), the problem was the "red badge" with the count.

@wendwarge did you received a new email and you cannot find the lab in backstage? Then please, share me your user registration email and the link in the email.

**Comment by openp2pdesign** [comment]
@wendwarge @ceritium do referees have two buttons **My Labs** and **My Labs to approve**?
This would probably make it clear and easy for everybody to use the backstage.

**Comment by openp2pdesign** [comment]
I have now two duplicates **Labs** buttons... why?

![screen shot 2017-01-09 at 17 20 19](https://cloud.githubusercontent.com/assets/1458229/21773583/f430399e-d68f-11e6-85b7-7d83861ae21f.png)

**Comment by wendwarge** [comment]
Same view, attached, different than Massimo. no red button, no extra tab.
Also, emails still going to everyone listed at our lab.
fablabwgtn@massey.ac.nz

**Comment by openp2pdesign** [comment]
Let's recap:

-  `Referee Labs` should see two buttons in the backstage: _My Labs_ and _My Labs to approve_
- In _My Labs to approve_ `Referee Labs` should see all the `Labs` that asked for their approval, even if a superadmin manually approved them. Here they should be able to see the user who approved them, see #194 
-  Regarding the e-mail notifications, let's discuss this on #195 

Is it correct? Anything more? 
Let's just focus on the structure now, we'll improve the UX later (UI, terms, and so on)

**Comment by wendwarge** [comment]
![issue 82](https://cloud.githubusercontent.com/assets/16007251/22233373/d66f633c-e254-11e6-896c-8a233a0ea472.JPG)
Nice one
