### ISSUE TITLE
Weeding out inactive labs

### ISSUE THREAD

**Issue by wendwarge** [fablabbcn/fablabs#84]
could we have a system where inactive labs on the site can be flagged for removal? Maybe it could be integrated with Francisco's planned lab #78

**Comment by TheBeachLab** [comment]
+1 @wendwarge but if fablabs.io does not add the mobile fab lab category request that I made some time ago I will be wiped out soon :P

**Comment by openp2pdesign** [comment]
Related to #96 and #101

**Comment by openp2pdesign** [comment]
Mobile Lab category request at #65

**Comment by openp2pdesign** [comment]
For the moment, we though that the _Discuss_ section should be used for this. Each `Lab` has a thread in _Discuss_ and it is embedded also on its page, and everybody should use that thread for not only talking about or with the `Lab`, but also for notifying fake or closed `Labs` (and then after the discussion the superadmins will manually handle the situation).
