### ISSUE TITLE
Npm/bower

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#91]
Can we move the [vendor/assets](https://github.com/fablabbcn/fablabs/tree/master/vendor/assets) folder to a npm/bower management?

**Comment by hiromipaw** [comment]
Why would you want to do that if no node packages are used at the moment? Also in the case you want to use gulp or some assets management system the new front end is already using that.

**Comment by openp2pdesign** [comment]
ok, great, I just saw that bower is used [on the frontend](https://github.com/fablabbcn/fablabs-ui/blob/master/bower.json). No problem then :-)

**Comment by openp2pdesign** [comment]
... so I guess that the [vendor/assets](https://github.com/fablabbcn/fablabs/tree/master/vendor/assets) could be removed... and I guess also that it is still part of the existing platform and not of the future one... is it correct?

@hiromipaw could you please explain very very quickly what each branch is about? Also for the other future developers

**Comment by openp2pdesign** [comment]
Now needed for #113

**Comment by openp2pdesign** [comment]
Bower is now in place for #113 since 96d72bbf01c261ea7332be3c1274db982d9d707d

We should add the _vendor/assets/bower_components_ folder to _.gitignore_ in order to **not** include the packages in the repo: we just need them in the server.

We should check that the deploy does a `bower install` after the commits in order to update the packages on the server. @ceritium could you please check this?
