### ISSUE TITLE
Move referees / supernodes from hardcoded to db

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#93]
At the moment [referees are hardcoded](https://github.com/fablabbcn/fablabs/blob/d8f2ab6aa1808288735d25f92a7fe6864c4af511/app/models/lab.rb#L198), we should move them to a db / backstage editing page

**Comment by openp2pdesign** [comment]
Can we have a "Referee Labs" checkbox here, similar to the Discourse ones, for seeing which are the `Referee Labs`? Otherwise it's hard to check them... The checkbox on each `Lab` edit page for making it or not a `Referee Lab` is fine.

![screen shot 2016-12-21 at 18 45 15](https://cloud.githubusercontent.com/assets/1458229/21399851/b2600364-c7ad-11e6-98c0-3ad2212c41be.png)

**Comment by ceritium** [comment]
Ok
