### ISSUE TITLE
Cookie policy warning is missing

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#98]
Add [this cookie policy warning plugin](https://silktide.com/tools/cookie-consent/), that redirects to the specific page with the policies.

**Comment by openp2pdesign** [comment]
We would need a deploy not just for the new policies / TOS but also for d92229d8f92c096002a707821bc7814b4995a1c7.. just to be sure

**Comment by openp2pdesign** [comment]
Pages are online, but the [this cookie policy warning plugin](https://silktide.com/tools/cookie-consent/), that redirects to the specific page with the policies seems to be still missing.. could you check @ceritium?

**Comment by ceritium** [comment]
I deployed it right now.

**Comment by openp2pdesign** [comment]
amazing! thanks
