### ISSUE TITLE
Improve user management

### ISSUE THREAD

**Issue by openp2pdesign** [fablabbcn/fablabs#99]
The `User` management section is quite limited, `Users` cannot be deleted for example, or they cannot delete themselves. Some `Users` are duplicated, and this causes problems.

This should be improved.

**Comment by openp2pdesign** [comment]
Admins should be able to edit not only the details of the users, but also their roles and permissions in fablabs.io from the backend. Now I have to ask this to the developer, it's too complicated.

**Comment by openp2pdesign** [comment]
Permissions by role are hardcoded, so at the moment it's hard to move everything to the backend... let's not change this at the moment, let's just focus on the role of each user (and make it editable by superadmins in the _Backstage_).

**Comment by openp2pdesign** [comment]
It is still not possible to see or change the role of a user..

![screen shot 2016-12-22 at 18 08 01](https://cloud.githubusercontent.com/assets/1458229/21433834/be7b37e4-c871-11e6-98fd-512db0765d37.png)

Can we also have a paginated list of users? now it loads all users in one page (+10,000 users!!)

**Comment by openp2pdesign** [comment]
In the user list, after the _Joined_ column, there should be a _Role_ column

![screen shot 2016-12-22 at 18 10 55](https://cloud.githubusercontent.com/assets/1458229/21433896/104d5d9a-c872-11e6-88ed-864c2c84bcff.png)

**Comment by openp2pdesign** [comment]
... and it would be great to have checkboxes in the user list, in order to filter by role (like with the Discourse id)

**Comment by ceritium** [comment]
> It is still not possible to see or change the role of a User..

You have to be `superadmin`, I can change it to `admin` role

**Comment by ceritium** [comment]
> Can we also have a paginated list of Users? now it loads all Users in one page (+10,000 users!!)

OK

**Comment by ceritium** [comment]
> In the User list, after the Joined column, there should be a Role column

OK

**Comment by ceritium** [comment]
> ... and it would be great to have checkboxes in the User list, in order to filter by role (like with the Discourse id for the Lab list)

Checkboxes or a select?

**Comment by openp2pdesign** [comment]
> You  have to be `superadmin`, I can change it to `admin` role

... am I not `superadmin`?

**Comment by openp2pdesign** [comment]
> Checkboxes or a select?

Yes, select is a better option!

**Comment by ceritium** [comment]
Closed with: https://github.com/fablabbcn/fablabs/pull/203

**Comment by openp2pdesign** [comment]
The _Surname_ field disappeared, we can now only search by _First Name_, we need it back:

![screen shot 2017-01-10 at 19 17 44](https://cloud.githubusercontent.com/assets/1458229/21818872/c1348286-d769-11e6-82e5-87608c78d30e.png)

**Comment by ceritium** [comment]
According to the [history](https://github.com/fablabbcn/fablabs/commits/master/app/views/backstage/users/index.html.haml) the form never included a Surname field. Anyway I can add the field https://github.com/fablabbcn/fablabs/issues/220
